### PR TITLE
Update dependencies and cater for webpack usage

### PR DESCRIPTION
**Pull request by schoenkaft**
- Upgraded all dependencies;
- Added `.mjs` to all imports, which caters for proper usage with webpack (React, Next.js, etc...); both ways of importing functions mentioned in the README should work;
- Swapped Travis in favour of GitHub actions;
- Tested in both a React (webpack) and existing vanilla JS (Gulp) project.

Not sure about versioning. Maybe minor? Not breaking as far as I've tested (🤞), but might be more significant than a bugfix? Or maybe not... 
Whichever suits you (`yarn publish` + push incl. tags) 👋

### CODE REVIEW

**Comment by schoenkaft** [comment]
Also copied all doc functions to the main README to improve SEO and make it a bit more clear from the root what's included.

PS: I just saw that there is already a PR (#34) for a part of this PR, woops 😄

**Review by harmenjanssen — APPROVED** [review]
Great, Koen, thanks again! 🙌

I've merged #34 first indeed, to encourage our community of OS contributors. 🙂

**Comment by harmenjanssen** [comment]
Weirdly, `yarn publish` gave me an `index.mjs` file containing a diff where all `mjs` extensions were removed... 🤔 
I have not committed that one. `yarn publish` shouldn't affect the codebase at all, right?

**Comment by schoenkaft** [comment]
> Weirdly, `yarn publish` gave me an `index.mjs` file containing a diff where all `mjs` extensions were removed... 🤔 I have not committed that one. `yarn publish` shouldn't affect the codebase at all, right?

Hmm,  I was going to say: sounds odd indeed. As far as I know it should only update the `package.json` with the newly chosen version in semver format, which it will automagically create a commit + tag for.

But... after test-running `yarn publish` myself, I see I've create this magic script in the past which is called `generate-index.js`, which runs via the `prepack` hook. It's a failsafe to make sure that newly added functions are indeed exposed in the published package, if one were ever to forget to also add it to the main index. 

Merge #36; no further publish needed afterwards 👋

**Comment by harmenjanssen** [comment]
Of course, that's it. 🙂 
Thanks for getting to the bottom!

**Pull request merged**
